server:
  tomcat: #tomact 服务器的配置
    relaxed-query-chars: '|,{,},[,]'  #进行get请求到时候 如何参数包含[,{,},] 认为是正常的
  port: 7245 # 端口

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/IS_lab1
    username: postgres
    password: s336262

#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5433/s336179
#    username: s336179
#    password: MsTFJKU3Kuh3emV9

  jackson: # json序列号配置
    property-naming-strategy: UPPER_CAMEL_CASE #设置大写开头的命名风格
    date-format: yyyy-MM-dd HH:mm:ss #设置标准的时间格式
    time-zone: Asia/Shanghai #时间对于的时区

mybatis-plus: #操作数据库的ORM框架 mybatis
  mapper-locations: mapper/*.xml #配置对于的mapper文件位置
  global-config: #mybatis的全局配置
    db-config: #数据库的配置
      table-prefix:   #表前面是否加前缀  如果不配置为空 会导致查询的sql表前面带有特定 前缀
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: false         #是否转换成大小写
  type-aliases-package: com.example.web.entity  #实体存储的包位置

  jpa:
    hibernate:
      ddl-auto: update  # Hibernate 自动管理数据库架构（开发阶段使用）
    show-sql: true  # 输出 SQL 查询日志
    properties:
      hibernate:
        format_sql: true  # 格式化 SQL 查询
    transaction:
      enabled: true  # 启用事务管理

      # minio 文件存储配置信息
minio:
  endpoint: http://127.0.0.1:9000
  url: http://localhost:9000
  accessKey: cD4GnOxBIg0NZJIoK2tM
  secretKey: tBsUYy6G7sXLaEVyQbP9JVkndft8GrKP2J49FJij
  bucketName: is-lab